### ISSUE TITLE
Update page.hiveteam.html

### ISSUE THREAD

**Issue by HadleyKing** [GW-HIVE/GW-HIVE.github.io#40]
Initiated by #39

**Comment by HadleyKing** [comment]
@Xifang11
Check the test site and make sure your changes are visible and correct.

**Comment by Xifang11** [comment]
@HadleyKing 
Checked the test site - It doesn't seem like the changes took effect. Did I miss a step?

**Comment by HadleyKing** [comment]
Looks good to me now.
